"""Little fixes 2

Revision ID: 09e52ce6b84b
Revises: 7259837203b0
Create Date: 2022-09-11 22:00:50.086516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09e52ce6b84b'
down_revision = '7259837203b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('url', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'url')
    # ### end Alembic commands ###
