"""Add CreatedAt in followers

Revision ID: 64358d86e745
Revises: c4afee59643d
Create Date: 2022-09-11 21:36:19.877903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64358d86e745'
down_revision = 'c4afee59643d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('followers', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('followers', 'created_at')
    # ### end Alembic commands ###
