"""Little fixes

Revision ID: 7259837203b0
Revises: 8f96c7bdcdd4
Create Date: 2022-09-11 21:54:26.265701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7259837203b0'
down_revision = '8f96c7bdcdd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('users', 'desciption')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('desciption', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'description')
    op.drop_column('posts', 'description')
    # ### end Alembic commands ###
